name: Remote Desktop
run-name: ${{ inputs.os }}

defaults:
  run:
    shell: bash --noprofile --norc -euo pipefail {0}

on:
  workflow_dispatch:
    inputs:
      os:
        description: Operating system
        type: choice
        required: true
        default: windows-latest
        options:
          - windows-latest
          - ubuntu-latest
          - macos-latest

      username: martin
        description: Username
        type: string
        required: true

      password:qwert12345
        description: Password
        type: string
        required: true

jobs:
  job:
    name: URL
    runs-on: ${{ inputs.os }}

    environment:
      name: ${{ github.run_id }}

    permissions:
      contents: read
      deployments: write

    env:
      PORT: 8080

    steps:
      - name: Start tunnel
        id: tunnel
        env:
          METRICS_URL: "localhost:8081"
        run: |
          case "$RUNNER_OS" in
            Windows)
              CLOUDFLARED=./cloudflared.exe

              curl -fsSL \
                "https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-windows-amd64.exe" \
                -o "${CLOUDFLARED}"
              ;;

            Linux)
              CLOUDFLARED=./cloudflared

              curl -fsSL \
                "https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64" \
                -o "${CLOUDFLARED}"
              ;;

            macOS)
              CLOUDFLARED=./cloudflared

              curl -fsSL \
                "https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-darwin-arm64.tgz" |
                tar -xz
              ;;
          esac

          chmod +x "${CLOUDFLARED}"

          "${CLOUDFLARED}" tunnel \
            --metrics="${METRICS_URL}" \
            --url "http://localhost:${PORT}" &

          until JSON="$(curl -sS "${METRICS_URL}/quicktunnel")"; do
            sleep 0.1
          done

          HOSTNAME="$(jq -r '.hostname' <<< "${JSON}")"
          TUNNEL_URL="https://${HOSTNAME}"

          echo "url=${TUNNEL_URL}" >> "$GITHUB_OUTPUT"

      - name: Run remote desktop
        env:
          GH_TOKEN: ${{ github.token }}
          GITHUB_TOKEN: ${{ github.token }}
          TUNNEL_URL: ${{ steps.tunnel.outputs.url }}
        run: |
          export USERNAME=$(jq -r '.inputs.username // ""' "$GITHUB_EVENT_PATH")
          echo "::add-mask::${USERNAME}"

          export PASSWORD=$(jq -r '.inputs.password // ""' "$GITHUB_EVENT_PATH")
          echo "::add-mask::${PASSWORD}"

          case "$RUNNER_OS" in
            Linux)
              ZIP_NAME="os-in-browser-linux-x64-1.0.0.zip"
              ;;

            Windows)
              ZIP_NAME="os-in-browser-win32-x64-1.0.0.zip"
              ;;

            macOS)
              ZIP_NAME="os-in-browser-darwin-arm64-1.0.0.zip"
              ;;
          esac

          gh release download \
            --repo "$GITHUB_REPOSITORY" \
            --pattern "$ZIP_NAME" \
          || gh release download \
            --repo "kingdudely/os-in-browser" \
            --pattern "$ZIP_NAME"

          unzip -q "$ZIP_NAME" || {
            status=$?
            if [ "$status" -ne 1 ]; then
              exit "$status"
            fi
          }

          case "$RUNNER_OS" in
            Linux)
              sudo apt-get update

              sudo apt-get install -y --no-install-recommends \
                icewm \
                xvfb \
                libx11-6 \
                libxtst6 \
                libxfixes3

              read -r DISPLAY_NUMBER < <(
                Xvfb \
                  -displayfd 1 \
                  -screen 0 1920x1080x24 \
                  +extension XTEST \
                  +extension XFIXES \
                  -nolisten tcp
              )

              export DISPLAY=":$DISPLAY_NUMBER"

              icewm-session &

              ./os-in-browser-linux-x64/os-in-browser --no-sandbox

              ;;

            Windows)
              ./os-in-browser-win32-x64/os-in-browser.exe

              ;;

            macOS)
              chmod +x ./os-in-browser.app/Contents/MacOS/os-in-browser
              ./os-in-browser.app/Contents/MacOS/os-in-browser
              ;;
          esac
